name: Tests

on:
  push:
    paths:
      - 'Task 8/**'
  pull_request:
    paths:
      - 'Task 8/**'

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22.5'

      - name: Install MongoDB Client
        run: |
          choco install mongodb --version 4.4.6
          mongosh --version

      - name: Initialize MongoDB
        run: |
          mongosh --host localhost:27017 -u admin -p admin --authenticationDatabase admin --eval "db = db.getSiblingDB('APP-DB'); db.createUser({ user: 'APP-USERNAME', pwd: 'APP-PASSWORD', roles: [{ role: 'readWrite', db: 'APP-DB' }] }); db.createCollection('APP-COLLECTION');"

      - name: Cache Go Modules
        uses: actions/cache@v3
        with:
          path: |
            **/go.sum
            **/go.mod
          key: ${{ runner.os }}-go-modules-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-modules-

      - name: Install Go Modules
        run: go mod download

      - name: Run Tests
        run: go test ./...
